-- El empaque tiene que poder nacer sin internet, y para eso el id lo pone el
-- cliente.
--
-- `proveedor_producto` nacio con `id bigint generated ALWAYS as identity`, y
-- eso PROHIBE que la fila traiga su propio id. Esta aplicacion es
-- offline-first: cada pantalla genera el id con `Date.now()` y `enqueueAction`
-- guarda la fila en Dexie -cuya clave primaria es `id`- antes de encolar el
-- upsert. Con `always`:
--
--   * `localDB.proveedor_producto.put(fila)` sin `id` revienta, y el `catch` de
--     `enqueueAction` solo hace `console.error`: la pantalla dice que guardo y
--     no hay nada guardado.
--   * y si la fila trajera id, Postgres rechazaria el upsert entero.
--
-- O sea: el fallo de siempre -ni excepcion visible ni log que nadie lea- en una
-- tabla recien creada. Se encontro comparando la tabla nueva con sus dos
-- vecinas ANTES de escribir la pantalla: `proveedores` y `productos` son las
-- dos `by default`, y esta era la unica `always` del esquema.
--
-- `by default` deja las dos cosas: si la fila trae id se respeta -que es el
-- caso offline-, y si no, la secuencia lo pone.
--
-- Aguanta la segunda pasada: `set generated by default` sobre una columna que
-- ya lo esta no cambia nada.

alter table public.proveedor_producto
  alter column id set generated by default;
